import os
from typing import List, Optional
from pii_mask import PIIMask, RedactedSpan


class PDFExporter:
    REDACTED_STYLE = {
        "fill_color": (0, 0, 0),
        "text_color": (0, 0, 0),
        "font_size": 10,
    }
    NORMAL_STYLE = {
        "font_size": 10,
    }
    HEADER_STYLE = {
        "font_size": 14,
    }

    def __init__(self):
        self.fpdf_available = self._check_fpdf()

    def _check_fpdf(self) -> bool:
        try:
            import fpdf
            return True
        except ImportError:
            return False

    def export_redacted_pdf(self, original_text: str, redacted_text: str,
                            spans: list, output_path: str,
                            title: str = "Redacted Transcript") -> Optional[str]:
        if not self.fpdf_available:
            raise RuntimeError(
                "fpdf2 is required for PDF export. Install: pip install fpdf2"
            )
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=20)

        pdf.set_font("Helvetica", "B", self.HEADER_STYLE["font_size"])
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, "Original Transcript", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", self.NORMAL_STYLE["font_size"])

        lines = original_text.split("\n")
        for line in lines:
            if line.strip():
                pdf.multi_cell(0, 5, line.strip())
        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, "Redacted Transcript", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        spans_sorted = sorted(spans, key=lambda s: s["start"] if isinstance(s, dict) else s.start)
        prev_end = 0

        pdf.set_font("Helvetica", "", self.NORMAL_STYLE["font_size"])
        for span in spans_sorted:
            start = span["start"] if isinstance(span, dict) else span.start
            end = span["end"] if isinstance(span, dict) else span.end
            label = span["label"] if isinstance(span, dict) else span.label

            normal_text = redacted_text[prev_end:start]
            if normal_text:
                pdf.multi_cell(0, 5, normal_text)

            tag = f"[{label}_REDACTED]"
            pdf.set_fill_color(*self.REDACTED_STYLE["fill_color"])
            pdf.set_text_color(*self.REDACTED_STYLE["text_color"])
            pdf.cell(pdf.get_string_width(tag) + 2, 5, tag, fill=True)
            pdf.set_text_color(0, 0, 0)
            prev_end = end

        remaining = redacted_text[prev_end:]
        if remaining:
            pdf.multi_cell(0, 5, remaining)

        pdf.ln(5)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 5, f"Generated by Privacy-Preserving Voice Assistant - IIT BHU",
                 new_x="LMARGIN", new_y="NEXT")

        pdf.output(output_path)
        return output_path

    def export_redacted_report_pdf(self, report: dict, output_path: str) -> Optional[str]:
        if not self.fpdf_available:
            raise RuntimeError("fpdf2 is required for PDF export")
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=20)

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Redaction Report", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(5)

        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Duration: {report.get('duration_seconds', 'N/A')}s", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Words: {report.get('num_words', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"PII Items Found: {report.get('pii_count', 0)}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"PII Summary: {report.get('pii_summary', 'None')}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, "Original Transcript", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, report.get("original_text", ""))
        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, "Redacted Transcript", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, report.get("redacted_text", ""))

        pdf.output(output_path)
        return output_path
